export const books = [
  {
    id: '1',
    title: 'Atomic Habits',
    author: 'James Clear',
    coverImage: '/images/books/atomic-habits.jpg',
    totalPages: 320,
    currentPage: 120,
    progress: 37,
    status: 'reading',
    startedAt: '2026-03-10',
  },
  {
    id: '2',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    coverImage: '/images/books/clean-code.jpg',
    totalPages: 464,
    currentPage: 150,
    progress: 32,
    status: 'reading',
    startedAt: '2026-03-05',
  },
  {
    id: '3',
    title: 'Deep Work',
    author: 'Cal Newport',
    coverImage: '/images/books/deep-work.jpg',
    totalPages: 304,
    currentPage: 80,
    progress: 26,
    status: 'reading',
    startedAt: '2026-03-12',
  },
];
